sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 10.13.0

script:
  - npm test --silent

notifications:
  webhooks:
    - https://de45c914.ngrok.io/taskbook/travis/notifications
